apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: heapster-grafana
  namespace: kube-system
  labels:
    app: heapster-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heapster-grafana
  template:
    metadata:
      labels:
        app: heapster-grafana
      annotations:
       seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      containers:
      - name: grafana
        image: k8s.gcr.io/heapster-grafana-amd64:v4.4.1
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
        env:
        - name: INFLUXDB_SERVICE_URL
          value: http://heapster-influxdb:8086
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
        - name: GF_SERVER_ROOT_URL
          value: /
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
      volumes:
      - name: grafana-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: heapster-grafana
  namespace: kube-system
  labels:
    app: heapster-grafana
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: heapster-grafana
---
# Create the ingress resource
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: heapster
  namespace: kube-system
spec:
  rules:
  - host: heapster.apps.olly.dtcntr.net
    http:
      paths:
      - backend:
          serviceName: heapster-grafana
          servicePort: 80
