apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
  labels:
    app: heapster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heapster
  template:
    metadata:
      labels:
        app: heapster
      annotations:
       seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: k8s.gcr.io/heapster-amd64:v1.5.4
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - "--source=kubernetes.summary_api:https://10.96.0.1?inClusterConfig=true&kubeletHttps=true&kubeletPort=10250"
        - "--sink=influxdb:http://heapster-influxdb.kube-system.svc:8086"
        - "--vmodule=*=4"
---
apiVersion: v1
kind: Service
metadata:
  name: heapster
  namespace: kube-system
  labels:
    app: heapster
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: heapster
