apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: heapster
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: heapster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: k8s.gcr.io/heapster-amd64:v1.5.0
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - "--source=kubernetes:https://10.96.0.1?inClusterConfig=false&kubeletHttps=true&kubeletPort=10250&auth="
        - "--sink=influxdb:http://monitoring-influxdb.heapster.svc:8086"
        - "--cert-dir=/srv/kubernetes/"
          #- "--tls-ca-file=/srv/kubernetes/swarm-root-ca.crt"  
          #- "--tls-cert-file=/srv/kubernetes/swarm-node.crt"
          #- "--tls-private-key-file=/srv/kubernetes/swarm-node.key"
        - "--vmodule=*=4"
        volumeMounts:
        - name: heapster-certs
          mountPath: /srv/kubernetes/
          readOnly: true
      volumes:
      - name: heapster-certs
        hostPath:
          path: /var/lib/docker/swarm/certificates
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: heapster
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster
