apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: heapster-influxdb
  namespace: kube-system
  labels:
    app: heapster-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heapster-influxdb
  template:
    metadata:
      labels:
        app: heapster-influxdb
      annotations:
       seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      containers:
      - name: influxdb
        image: k8s.gcr.io/heapster-influxdb-amd64:v1.5.2
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: heapster-influxdb
  namespace: kube-system
  labels:
    app: heapster-influxdb
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: heapster-influxdb
