apiVersion: extensions/v1beta1
kind: Ingress
metadata:
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
  name: heapster
  namespace: kube-system
spec:
  rules:
  - host: heapster.k8s.olly.dtcntr.net
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoring-grafana
          servicePort: 80
