---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        k8s-app: metrics-server
    spec:
      serviceAccountName: metrics-server
      # Because DNS doesn't work in my env I manually define hosts here. 
      # you probably don't need this bit....
      hostAliases:
      - ip: "172.31.13.181"
        hostnames:
        - "manager-01.local"
      - ip: "172.31.1.128"
        hostnames:
        - "worker-01.local"
      - ip: "172.31.8.8"
        hostnames:
        - "dtr-01.local"
      volumes:
      - name: tmp-dir
        emptyDir: {}
      containers:
      - name: metrics-server
        image: gcr.io/google_containers/metrics-server-amd64:v0.3.0
        imagePullPolicy: Always
        command:
        - /metrics-server
        - "--kubelet-port=10250"
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
