apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: stress-test
  name: stress-ng
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
      - name: stress
        image: lorel/docker-stress-ng
        command: ["/usr/bin/stress-ng"]
#        args: ["--vm", "1", "--vm-bytes", "536870912", "--timeout", "0", "-v"]
        args: ["--vm", "1", "--vm-bytes", "524288000", "--timeout", "0", "-v"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "200m"
