---
apiVersion: v1
kind: Service
metadata:
  name: metrics-api
  namespace: monitoring
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: metrics-api
  clusterIP: None
