kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-role-binding
roleRef:
  kind: ClusterRole
  name: psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: fred
  namespace: default
