[auth]
  default_new_user_role = "restrictedcontrol"
  backend = "managed"
  samlEnabled = false
  samlLoginText = ""
  [auth.sessions]
    lifetime_minutes = 60
    renewal_threshold_minutes = 20
    per_user_limit = 10
  [auth.saml]
    idpMetadataURL = ""
    spHost = ""
    rootCerts = ""
    tlsSkipVerify = false

[[registries]]
  host_address = "172.31.8.8"
  service_id = "52374cd4-4ce4-44d7-8eb6-64d80d82ef65"
  ca_bundle = "-----BEGIN CERTIFICATE-----\nMIICDzCCAbSgAwIBAgIRANp0yNREHETV65dzwZASeoYwCgYIKoZIzj0EAwIwRzEL\nMAkGA1UEBhMCVVMxFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xDzANBgNVBAoTBkRv\nY2tlcjEPMA0GA1UECxMGRG9ja2VyMB4XDTE4MDkxMzE1MDgxM1oXDTE5MDkxMzE1\nMDgxM1owRzELMAkGA1UEBhMCVVMxFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xDzAN\nBgNVBAoTBkRvY2tlcjEPMA0GA1UECxMGRG9ja2VyMFkwEwYHKoZIzj0CAQYIKoZI\nzj0DAQcDQgAEaqqZeQEJ9+MG+v/a3QG6irz4v0d/hn9fzeQMkt4TeS/N9ruA3N9g\nmS+578SqT48JBSlM4C3+lzdDnqto+0TqlKOBgDB+MA4GA1UdDwEB/wQEAwICpDAP\nBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSaPt+lSQIe9joitjtHLa0BVUVSozA8\nBgNVHREENTAzggUqLmNvbYIHKi4qLmNvbYILZXhhbXBsZS5jb22CBSouZHRyggcq\nLiouZHRyhwSsEQABMAoGCCqGSM49BAMCA0kAMEYCIQCvrlKiNPrjwnKIvaOfR7Zv\nue8zv8fL+m8QjZB7mb87egIhAO0P3qOOPCMVeahKizcXoOsQKZ/WjOIX8XvUcVCb\nPfIp\n-----END CERTIFICATE-----\n"
  batch_scanning_data_enabled = false

[[registries]]
  host_address = "dtr.beta.olly.dtcntr.net"
  service_id = "52374cd4-4ce4-44d7-8eb6-64d80d82ef65"
  ca_bundle = "-----BEGIN CERTIFICATE-----\nMIIDwjCCAqqgAwIBAgIUYMBQd1vl8D2XXPmj2trlVd8apjYwDQYJKoZIhvcNAQEL\nBQAwZzELMAkGA1UEBhMCVUsxFDASBgNVBAgTC0xvbmRvbnNoaXJlMQ8wDQYDVQQH\nEwZMb25kb24xETAPBgNVBAoTCE9sbHlzTGFiMQwwCgYDVQQLEwNEREMxEDAOBgNV\nBAMTB09sbHlzQ0EwHhcNMTcwNjA3MTc1NjAwWhcNMjIwNjA2MTc1NjAwWjBnMQsw\nCQYDVQQGEwJVSzEUMBIGA1UECBMLTG9uZG9uc2hpcmUxDzANBgNVBAcTBkxvbmRv\nbjERMA8GA1UEChMIT2xseXNMYWIxDDAKBgNVBAsTA0REQzEQMA4GA1UEAxMHT2xs\neXNDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMJj4f5/Do2iNJQ+\nEo+0wiWKLQq02koOOtngN9y9ilVH8HrKYiTRY6ehRgkMY2uRbf0gOCMG8b9cM40n\nI/fPX+bgZOdmP3O+O0iRq+jWKlO8Gbtaxc1x9LWBiUMedUF10ZQI8UPhY5rmsJBX\n5vORh0CJN+N6X4Q+aWaCpc3cXswx5fUX7WMuvtwWjoS9t9vNqwPWhzcTPoaAOYGO\nBv0w636uSoY9ebUh28jz/v1JGAt8qpYeYlRbhhzqZcCvxVGWobqIVm830ZSybe2X\nGELAoRTQeSsZmogATbiT+4i5vasm4QSHZzMSiyTGIquy+/8Phnxl901rGD7MsdsI\ny15hDpkCAwEAAaNmMGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C\nAQIwHQYDVR0OBBYEFK6bROLzypyYeP6Z709bfmBWku5kMB8GA1UdIwQYMBaAFK6b\nROLzypyYeP6Z709bfmBWku5kMA0GCSqGSIb3DQEBCwUAA4IBAQAsc2H5YpyWpYuP\nhDkk1uuYJKfLukqDWkBvWcVBr2bRfLT0X61tbIymYZYVZclJdlQz4OQGEXwBEfYD\niHZI7dLD05YJI1wrO0lQx2D5E/43DoBAvp4hNGYQdkzN2xYnezl1FrH9equpQQ/b\nYhsetVoaz9al8LnWqBWR29Uh4MQ6KKiwvgS49Zz/XgtFl1+uKnQ3pTEqCShgqfYD\n88tSBJabMEOnHxQmcDelmuvJV8M3o55UHIvF0z1UbopRat6dF4j6KifezR2UMWI9\nTXNEBs1pkBk1QhWLlbOHY8VpNS2f6j63ayoxIyRIjOSarn+E5lIhutdztS5VG7q+\nc3bQJPPS\n-----END CERTIFICATE-----\n"
  batch_scanning_data_enabled = false

[scheduling_configuration]
  enable_admin_ucp_scheduling = true
  default_node_orchestrator = "kubernetes"

[tracking_configuration]
  disable_usageinfo = false
  disable_tracking = false
  anonymize_tracking = false
  cluster_label = ""

[trust_configuration]
  require_content_trust = false

[log_configuration]
  protocol = ""
  host = ""
  level = "INFO"

[audit_log_configuration]
  level = "metadata"
  support_dump_include_audit_logs = false

[license_configuration]
  auto_refresh = false

[cluster_config]
  controller_port = 8443
  kube_apiserver_port = 6443
  swarm_port = 2376
  swarm_strategy = "spread"
  kv_timeout = 5000
  kv_snapshot_count = 20000
  profiling_enabled = false
  external_service_lb = ""
  metrics_retention_time = "24h"
  metrics_scrape_interval = "1m"
  rethinkdb_cache_size = "1GB"
  cloud_provider = ""
  cni_installer_url = ""
  pod_cidr = "192.168.0.0/16"
  calico_mtu = "1480"
  ipip_mtu = "1480"
  unmanaged_cni = false
  nodeport_range = "32768-35535"
  azure_ip_count = ""
  custom_kube_api_server_flags = ["--enable-admission-plugins=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota,PodNodeSelector,UCPAuthorization,CheckImageSigning,UCPNodeSelector,PodSecurityPolicy"]
  local_volume_collection_mapping = false
  manager_kube_reserved_resources = "cpu=250m,memory=2Gi,ephemeral-storage=4Gi"
  worker_kube_reserved_resources = "cpu=50m,memory=300Mi,ephemeral-storage=500Mi"
