apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
    - name:  privileged-pod
      image: alpine
      command:
        - sleep
        - "500000"
      securityContext:
        privileged: true
