apiVersion: v1
kind: Pod
metadata:
  name: uuid-pod
spec:
  containers:
    - name:  basic-pod
      image: ubuntu:latest
      command:
        - sleep
        - "50000"
  securityContext:
    runAsUser: 1000
