---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: createpvs
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - create
  - delete
  - watch
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jeff:createpvs
roleRef:
  kind: ClusterRole
  name: createpvs
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: jeff
