---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localvolume
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - create
  - delete
  - watch
    #---
    #kind: RoleBinding
    #apiVersion: rbac.authorization.k8s.io/v1
    #metadata:
    #  name: localvolume
    #  namespace: default
    #roleRef:
    #  kind: Role
    #  name: localvolume
    #  apiGroup: rbac.authorization.k8s.io
    #subjects:
    #- kind: ServiceAccount
    #  name: fluentd
    #  namespace: monitoring
